/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
    }
    interface MyHtmlWidget {
    }
    interface MyParsedWidget {
        /**
          * The first name
         */
        "first": string;
    }
    interface MyWidget {
        /**
          * The first name
         */
        "first": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyHtmlWidgetElement extends Components.MyHtmlWidget, HTMLStencilElement {
    }
    var HTMLMyHtmlWidgetElement: {
        prototype: HTMLMyHtmlWidgetElement;
        new (): HTMLMyHtmlWidgetElement;
    };
    interface HTMLMyParsedWidgetElement extends Components.MyParsedWidget, HTMLStencilElement {
    }
    var HTMLMyParsedWidgetElement: {
        prototype: HTMLMyParsedWidgetElement;
        new (): HTMLMyParsedWidgetElement;
    };
    interface HTMLMyWidgetElement extends Components.MyWidget, HTMLStencilElement {
    }
    var HTMLMyWidgetElement: {
        prototype: HTMLMyWidgetElement;
        new (): HTMLMyWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-html-widget": HTMLMyHtmlWidgetElement;
        "my-parsed-widget": HTMLMyParsedWidgetElement;
        "my-widget": HTMLMyWidgetElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
    }
    interface MyHtmlWidget {
    }
    interface MyParsedWidget {
        /**
          * The first name
         */
        "first"?: string;
    }
    interface MyWidget {
        /**
          * The first name
         */
        "first"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-html-widget": MyHtmlWidget;
        "my-parsed-widget": MyParsedWidget;
        "my-widget": MyWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-html-widget": LocalJSX.MyHtmlWidget & JSXBase.HTMLAttributes<HTMLMyHtmlWidgetElement>;
            "my-parsed-widget": LocalJSX.MyParsedWidget & JSXBase.HTMLAttributes<HTMLMyParsedWidgetElement>;
            "my-widget": LocalJSX.MyWidget & JSXBase.HTMLAttributes<HTMLMyWidgetElement>;
        }
    }
}
